version: "3.9"
services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - ../../.env
    ports: ["8000:8000"]
    depends_on: [redis, qdrant, opensearch, prometheus]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports: ["9200:9200"]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
