name: CI
on: [push, pull_request]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r requirements.txt
      - run: echo "No tests yet"
      - name: Build API Image
        run: docker build -f infra/docker/api.Dockerfile -t pantry/api:ci .
